--- 
title: "Formatting References"
author: Texas Water Resources Institute
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: book.yaml
url: https://txwri.github.io/twj-csl/
description: |
  Provides formatting examples for internally produced reports.
csl: ../texas-water-journal-name-year.csl
link-citations: true
---

# About

This is _example_ documentation for in-text citations and reference styles used in Texas Water Journal submissions.

## Reccomended Usage 


The Texas Water Journal uses the Council of Science Editors (CSE) Scientific Style and Format manual, 8th edition, with some exceptions. Please see the Texas Water Journal's detailed style guidelines and exceptions for more information about style and word usage, including punctuation, use of numbers and units of measure, and in-text and reference list examples. The Texas Water Journal also accepts Bluebook for legal articles.

### In-Text References

 - The *Texas Water Journal* uses the Name–Year in-text reference system, meaning that the basic form is *Author Last Name Year*; for two authors, use *First Author Last Name and Second Author Last Name Year*; for more than two use *First Author Last Name et al. Year*; for an organization, use *Organization Initials Year*.

Examples:
Smith 2013
Smith and Jones 2013
Smith et al. 2013
EPA 2013

- When several in-text references occur at the same point, give them in chronologic sequence from earliest to latest, separated by semicolons (see [CSE Section 29.2.1.2.9](https://www.scientificstyleandformat.org/book/ed8/pt4/ch29/asec02.html#c2902010200). For references published in the same year, list in alphabetical order.

Example:
Improved estimates of climate variability and trends should prepare authorities to cope with ongoing climate change, which is predicted to increase aridity in the Southwest (IPCC 2007b; Seager et al. 2008; Banner et al. 2010) and may help them to prepare mitigation strategies (IPCC 2007a; Furniss et al. 2010).

### References: Reference List

For more on in-text citations and reference lists, see [CSE Chapter 29](https://www.scientificstyleandformat.org/book/ed8/pt4/ch29/asec01.html).

Components of end references and their sequence

| Books and other monographs | Journal and newspaper articles |
|----------------------------|--------------------------------|
| Author(s) | Author(s)   |
| Title      | Article title  |
| Content designator | Content designator  |
| Medium designator* | Journal or newspaper title |
| Edition | Edition |
| Secondary author | Medium designator* |
| Place of publication | Date |
| Publisher | Volume |
| Date | Issue |
| Extent (pagination) | Location (pagination) |
| Physical description | Physical description |
| Series | Notes |
| Notes | |


 - All references from the internet should include date accessed. Because inclusion of a 
URL in a reference to an online source makes the medium obvious, it is not necessary to 
include “Internet” as a medium designator for online sources.
 - The basic format for journal article is:
Last Name Initials (no periods), Last Name Initials. Year. Title of article (in sentence 
case). Journal Title (spelled out, no italics). (period) Vol (issue):page numbers 
(separated by hyphen). Available from: DOI link.
 - Use sentence case for journal articles, book titles (capitalization should follow format of
a normal sentence).
 - Do NOT abbreviate journal titles.
 - In order to format personal author names, follow these examples:

Vincent T. DeVita, Jr. → DeVita VT Jr
John A. Addams III → Adams JA 3rd
Estelle Palmer-Canton → Palmer-Canton E
Jean-Louis Lagrot → Lagrot JL


## Bibliography Managers

There are multiple bibliography managers available to manage and format references. [Zotero](https://www.zotero.org/) and [Mendeley](https://www.mendeley.com/) use Citation Style Language (`.csl`) files to format references. A `.csl` file specific to texas Water Jounral's in-house reference style is available on [Github](https://raw.githubusercontent.com/TxWRI/csl/main/texas-water-journal-name-year.csl).
